project_id = "pfrdaarzcxxlxlhlfhoh"

[functions.generate-insights]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.upload-files-to-assistant]
verify_jwt = false

[functions.google-oauth-start]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = true

[functions.yt-backfill]
verify_jwt = true

[functions.yt-sync-daily]
verify_jwt = true